# Generated by Django 3.0.1 on 2020-01-05 19:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=200)),
                ('ext_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='AssetDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date of asset data')),
            ],
        ),
        migrations.CreateModel(
            name='AssetInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(choices=[('USD', 'USD')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=20)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetlogger.Asset')),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assetlogger.AssetDate')),
            ],
        ),
    ]
